#! /bin/sh
bspc rule -r "*"

# AUTOSTART 
sxhkd -c $HOME/.config/bspwm/sxhkdrc&
nitrogen --restore&
polybar -r bar&

# MONITORS
bspc monitor -d 1 2 3 4 5 6 7 8 9 
# bspc monitor NAME -d 0
# if there is more than one monitor you'll need to add more of these ^
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors  true

bspc config border_width         2
bspc config window_gap           0 
bspc config top_padding         27

bspc config pointer_modifier shift 
bspc config pointer_action1 move 
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config click_to_focus       true 

# RULES
bspc rule -a Gimp desktop='^9' state=floating follow=on
bspc rule -a Zathura state=tiled
